language: ruby

rvm:
  - 2.2.0
env:
  - DB=sqlite

script:
  - bundle exec rake test

before_script:
  - bundle exec rake db:migrate --trace RAILS_ENV=test
  - bundle exec rake db:test:prepare

notifications:
  email:
    recipients:
      - pedrodelyra@gmail.com
branches:
  only:
    - master
