#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook "nodejs"
cookbook "mongodb"
cookbook "git"

cookbook 'apt'
cookbook 'build-essential'
cookbook 'mysql', '5.5.3'
cookbook 'ruby_build', '2.2.0'
cookbook 'vim'
# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

 cookbook 'rvm',
   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
