Document: enem-amigo
Title: Debian enem-amigo Manual
Author: <insert document author here>
Abstract: This manual describes what enem-amigo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/enem-amigo/enem-amigo.sgml.gz

Format: postscript
Files: /usr/share/doc/enem-amigo/enem-amigo.ps.gz

Format: text
Files: /usr/share/doc/enem-amigo/enem-amigo.text.gz

Format: HTML
Index: /usr/share/doc/enem-amigo/html/index.html
Files: /usr/share/doc/enem-amigo/html/*.html
